/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mpayne' at '6/1/15 2:00 PM' with Gradle 2.4
 *
 * @author mpayne, @date 6/1/15 2:00 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
