//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 03:28:52 PM EDT 
//


package com.pml.services.security;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.pennmutual.services.xml.BaseXmlObject;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="system" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systems"
})
@XmlRootElement(name = "assignedSourceSystems", namespace = "security.services.pml.com")
public class AssignedSourceSystems
    extends BaseXmlObject
{

    @XmlElement(name = "system", namespace = "security.services.pml.com")
    protected List<String> systems;

    /**
     * Gets the value of the systems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSystems() {
        if (systems == null) {
            systems = new ArrayList<String>();
        }
        return this.systems;
    }

    public AssignedSourceSystems withSystems(String... values) {
        if (values!= null) {
            for (String value: values) {
                getSystems().add(value);
            }
        }
        return this;
    }

    public AssignedSourceSystems withSystems(Collection<String> values) {
        if (values!= null) {
            getSystems().addAll(values);
        }
        return this;
    }

}
