//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 03:28:52 PM EDT 
//


package com.pml.services.security;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pml.services.security package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pml.services.security
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link RolesCopy }
     * 
     */
    public RolesCopy createRolesCopy() {
        return new RolesCopy();
    }

    /**
     * Create an instance of {@link PayGroups }
     * 
     */
    public PayGroups createPayGroups() {
        return new PayGroups();
    }

    /**
     * Create an instance of {@link PayGroup }
     * 
     */
    public PayGroup createPayGroup() {
        return new PayGroup();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AssignedDepartments }
     * 
     */
    public AssignedDepartments createAssignedDepartments() {
        return new AssignedDepartments();
    }

    /**
     * Create an instance of {@link PmlName }
     * 
     */
    public PmlName createPmlName() {
        return new PmlName();
    }

    /**
     * Create an instance of {@link Managers }
     * 
     */
    public Managers createManagers() {
        return new Managers();
    }

    /**
     * Create an instance of {@link Manager }
     * 
     */
    public Manager createManager() {
        return new Manager();
    }

    /**
     * Create an instance of {@link Reports }
     * 
     */
    public Reports createReports() {
        return new Reports();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Delegators }
     * 
     */
    public Delegators createDelegators() {
        return new Delegators();
    }

    /**
     * Create an instance of {@link Delegator }
     * 
     */
    public Delegator createDelegator() {
        return new Delegator();
    }

    /**
     * Create an instance of {@link com.pml.services.security.UserBase.App }
     * 
     */
    public com.pml.services.security.UserBase.App createUserBaseApp() {
        return new com.pml.services.security.UserBase.App();
    }

    /**
     * Create an instance of {@link Delegates }
     * 
     */
    public Delegates createDelegates() {
        return new Delegates();
    }

    /**
     * Create an instance of {@link Delegate }
     * 
     */
    public Delegate createDelegate() {
        return new Delegate();
    }

    /**
     * Create an instance of {@link Hrinformation }
     * 
     */
    public Hrinformation createHrinformation() {
        return new Hrinformation();
    }

    /**
     * Create an instance of {@link SubscribedServices }
     * 
     */
    public SubscribedServices createSubscribedServices() {
        return new SubscribedServices();
    }

    /**
     * Create an instance of {@link AssignedSourceSystems }
     * 
     */
    public AssignedSourceSystems createAssignedSourceSystems() {
        return new AssignedSourceSystems();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

}
