//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 03:28:52 PM EDT 
//


package com.pml.services.security;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.pennmutual.services.xml.BaseXmlObject;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{security.services.pml.com}roles"/>
 *         &lt;element ref="{security.services.pml.com}rolesCopy"/>
 *         &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oldPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="termsAndConditionsFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currentTermCondFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="registered" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="confirmEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contractTerminatedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="challengeQuestion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="challengeResponse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="policyNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{security.services.pml.com}payGroups" minOccurs="0"/>
 *         &lt;element name="department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hireDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountingOfficeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="employeeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selfRegDone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regComplete" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loginLockedStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountDisabledStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postOfficeBox" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}address" minOccurs="0"/>
 *         &lt;element name="authCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}assignedDepartments" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}pmlName" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}managers"/>
 *         &lt;element ref="{security.services.pml.com}reports"/>
 *         &lt;element name="leadershipCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="leadershipCategoryOld" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primOfficeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primAgentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}location"/>
 *         &lt;element name="fieldStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="distChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htkRepId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htkContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pmlContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="piaContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="challengeQuestion2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="challengeResponse2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="imageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sitePhrase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cookie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lanUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}delegators"/>
 *         &lt;element ref="{security.services.pml.com}delegates"/>
 *         &lt;element name="aesToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{security.services.pml.com}hrinformation"/>
 *         &lt;element name="changePasswordOnNextLogin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passwordExpired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="passwordLastSetDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alternateEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{security.services.pml.com}subscribedServices"/>
 *         &lt;element name="userCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="msaExclusiveFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="realtimePosting" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{security.services.pml.com}assignedSourceSystems"/>
 *         &lt;element ref="{security.services.pml.com}status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roles",
    "rolesCopy",
    "dn",
    "name",
    "dob",
    "taxId",
    "password",
    "oldPassword",
    "clientId",
    "termsAndConditionsFlag",
    "currentTermCondFlag",
    "disabled",
    "registered",
    "confirmEmail",
    "contractTerminatedFlag",
    "emailAddress",
    "challengeQuestion",
    "challengeResponse",
    "lastName",
    "firstName",
    "middleName",
    "policyNo",
    "company",
    "companyCode",
    "payGroups",
    "department",
    "departmentCode",
    "fileNumber",
    "hireDate",
    "employeeId",
    "accountingOfficeCode",
    "employeeStatus",
    "phone",
    "selfRegDone",
    "regComplete",
    "userId",
    "loginLockedStatus",
    "accountDisabledStatus",
    "postOfficeBox",
    "address",
    "authCode",
    "prefix",
    "assignedDepartments",
    "pmlName",
    "managers",
    "reports",
    "leadershipCategory",
    "leadershipCategoryOld",
    "primOfficeCode",
    "primAgentCode",
    "location",
    "fieldStatus",
    "distChannel",
    "htkRepId",
    "htkContract",
    "pmlContract",
    "piaContract",
    "clientType",
    "challengeQuestion2",
    "challengeResponse2",
    "imageId",
    "sitePhrase",
    "cookie",
    "lanUser",
    "pin",
    "delegators",
    "delegates",
    "aesToken",
    "hrinformation",
    "changePasswordOnNextLogin",
    "passwordExpired",
    "passwordLastSetDate",
    "modifiedDate",
    "alternateEmailAddress",
    "subscribedServices",
    "userCategory",
    "msaExclusiveFlag",
    "realtimePosting",
    "assignedSourceSystems",
    "status"
})
@XmlRootElement(name = "User", namespace = "security.services.pml.com")
public class User
    extends BaseXmlObject
{

    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Roles roles;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected RolesCopy rolesCopy;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String dn;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String name;
    @XmlElement(namespace = "security.services.pml.com")
    protected String dob;
    @XmlElement(namespace = "security.services.pml.com")
    protected String taxId;
    @XmlElement(namespace = "security.services.pml.com")
    protected String password;
    @XmlElement(namespace = "security.services.pml.com")
    protected String oldPassword;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String clientId;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String termsAndConditionsFlag;
    @XmlElement(namespace = "security.services.pml.com")
    protected Boolean currentTermCondFlag;
    @XmlElement(namespace = "security.services.pml.com")
    protected Boolean disabled;
    @XmlElement(namespace = "security.services.pml.com")
    protected Boolean registered;
    @XmlElement(namespace = "security.services.pml.com")
    protected String confirmEmail;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String contractTerminatedFlag;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String emailAddress;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String challengeQuestion;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String challengeResponse;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String lastName;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String firstName;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String middleName;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String policyNo;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String company;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String companyCode;
    @XmlElement(namespace = "security.services.pml.com")
    protected PayGroups payGroups;
    @XmlElement(namespace = "security.services.pml.com")
    protected String department;
    @XmlElement(namespace = "security.services.pml.com")
    protected String departmentCode;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String fileNumber;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String hireDate;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String employeeId;
    @XmlElement(namespace = "security.services.pml.com")
    protected String accountingOfficeCode;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String employeeStatus;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String phone;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String selfRegDone;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String regComplete;
    @XmlElement(namespace = "security.services.pml.com")
    protected String userId;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String loginLockedStatus;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String accountDisabledStatus;
    @XmlElement(namespace = "security.services.pml.com")
    protected String postOfficeBox;
    @XmlElement(namespace = "security.services.pml.com")
    protected Address address;
    @XmlElement(namespace = "security.services.pml.com")
    protected String authCode;
    @XmlElement(namespace = "security.services.pml.com")
    protected String prefix;
    @XmlElement(namespace = "security.services.pml.com")
    protected AssignedDepartments assignedDepartments;
    @XmlElement(namespace = "security.services.pml.com")
    protected PmlName pmlName;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Managers managers;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Reports reports;
    @XmlElement(namespace = "security.services.pml.com")
    protected String leadershipCategory;
    @XmlElement(namespace = "security.services.pml.com")
    protected String leadershipCategoryOld;
    @XmlElement(namespace = "security.services.pml.com")
    protected String primOfficeCode;
    @XmlElement(namespace = "security.services.pml.com")
    protected String primAgentCode;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Location location;
    @XmlElement(namespace = "security.services.pml.com")
    protected String fieldStatus;
    @XmlElement(namespace = "security.services.pml.com")
    protected String distChannel;
    @XmlElement(namespace = "security.services.pml.com")
    protected String htkRepId;
    @XmlElement(namespace = "security.services.pml.com")
    protected String htkContract;
    @XmlElement(namespace = "security.services.pml.com")
    protected String pmlContract;
    @XmlElement(namespace = "security.services.pml.com")
    protected String piaContract;
    @XmlElement(namespace = "security.services.pml.com")
    protected String clientType;
    @XmlElement(namespace = "security.services.pml.com")
    protected String challengeQuestion2;
    @XmlElement(namespace = "security.services.pml.com")
    protected String challengeResponse2;
    @XmlElement(namespace = "security.services.pml.com")
    protected String imageId;
    @XmlElement(namespace = "security.services.pml.com")
    protected String sitePhrase;
    @XmlElement(namespace = "security.services.pml.com")
    protected String cookie;
    @XmlElement(namespace = "security.services.pml.com")
    protected String lanUser;
    @XmlElement(namespace = "security.services.pml.com")
    protected String pin;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Delegators delegators;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Delegates delegates;
    @XmlElement(namespace = "security.services.pml.com")
    protected String aesToken;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Hrinformation hrinformation;
    @XmlElement(namespace = "security.services.pml.com")
    protected String changePasswordOnNextLogin;
    @XmlElement(namespace = "security.services.pml.com", defaultValue = "false")
    protected Boolean passwordExpired;
    @XmlElement(namespace = "security.services.pml.com")
    protected String passwordLastSetDate;
    @XmlElement(namespace = "security.services.pml.com")
    protected String modifiedDate;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String alternateEmailAddress;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected SubscribedServices subscribedServices;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String userCategory;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String msaExclusiveFlag;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected String realtimePosting;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected AssignedSourceSystems assignedSourceSystems;
    @XmlElement(namespace = "security.services.pml.com", required = true)
    protected Status status;

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link Roles }
     *     
     */
    public Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roles }
     *     
     */
    public void setRoles(Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the rolesCopy property.
     * 
     * @return
     *     possible object is
     *     {@link RolesCopy }
     *     
     */
    public RolesCopy getRolesCopy() {
        return rolesCopy;
    }

    /**
     * Sets the value of the rolesCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RolesCopy }
     *     
     */
    public void setRolesCopy(RolesCopy value) {
        this.rolesCopy = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDob(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxId(String value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the oldPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldPassword() {
        return oldPassword;
    }

    /**
     * Sets the value of the oldPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldPassword(String value) {
        this.oldPassword = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the termsAndConditionsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsAndConditionsFlag() {
        return termsAndConditionsFlag;
    }

    /**
     * Sets the value of the termsAndConditionsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsAndConditionsFlag(String value) {
        this.termsAndConditionsFlag = value;
    }

    /**
     * Gets the value of the currentTermCondFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentTermCondFlag() {
        return currentTermCondFlag;
    }

    /**
     * Sets the value of the currentTermCondFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentTermCondFlag(Boolean value) {
        this.currentTermCondFlag = value;
    }

    /**
     * Gets the value of the disabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabled() {
        return (disabled == null) ? false : disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabled(Boolean value) {
        this.disabled = value;
    }

    /**
     * Gets the value of the registered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegistered() {
        return registered;
    }

    /**
     * Sets the value of the registered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegistered(Boolean value) {
        this.registered = value;
    }

    /**
     * Gets the value of the confirmEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmEmail() {
        return confirmEmail;
    }

    /**
     * Sets the value of the confirmEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmEmail(String value) {
        this.confirmEmail = value;
    }

    /**
     * Gets the value of the contractTerminatedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractTerminatedFlag() {
        return contractTerminatedFlag;
    }

    /**
     * Sets the value of the contractTerminatedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractTerminatedFlag(String value) {
        this.contractTerminatedFlag = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the challengeQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallengeQuestion() {
        return challengeQuestion;
    }

    /**
     * Sets the value of the challengeQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallengeQuestion(String value) {
        this.challengeQuestion = value;
    }

    /**
     * Gets the value of the challengeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallengeResponse() {
        return challengeResponse;
    }

    /**
     * Sets the value of the challengeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallengeResponse(String value) {
        this.challengeResponse = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the policyNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * Sets the value of the policyNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNo(String value) {
        this.policyNo = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the payGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PayGroups }
     *     
     */
    public PayGroups getPayGroups() {
        return payGroups;
    }

    /**
     * Sets the value of the payGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayGroups }
     *     
     */
    public void setPayGroups(PayGroups value) {
        this.payGroups = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the fileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * Sets the value of the fileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileNumber(String value) {
        this.fileNumber = value;
    }

    /**
     * Gets the value of the hireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHireDate() {
        return hireDate;
    }

    /**
     * Sets the value of the hireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHireDate(String value) {
        this.hireDate = value;
    }

    /**
     * Gets the value of the employeeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets the value of the employeeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeId(String value) {
        this.employeeId = value;
    }

    /**
     * Gets the value of the accountingOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingOfficeCode() {
        return accountingOfficeCode;
    }

    /**
     * Sets the value of the accountingOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingOfficeCode(String value) {
        this.accountingOfficeCode = value;
    }

    /**
     * Gets the value of the employeeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeStatus() {
        return employeeStatus;
    }

    /**
     * Sets the value of the employeeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeStatus(String value) {
        this.employeeStatus = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the selfRegDone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfRegDone() {
        return selfRegDone;
    }

    /**
     * Sets the value of the selfRegDone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfRegDone(String value) {
        this.selfRegDone = value;
    }

    /**
     * Gets the value of the regComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegComplete() {
        return regComplete;
    }

    /**
     * Sets the value of the regComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegComplete(String value) {
        this.regComplete = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the loginLockedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginLockedStatus() {
        return loginLockedStatus;
    }

    /**
     * Sets the value of the loginLockedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginLockedStatus(String value) {
        this.loginLockedStatus = value;
    }

    /**
     * Gets the value of the accountDisabledStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDisabledStatus() {
        return accountDisabledStatus;
    }

    /**
     * Sets the value of the accountDisabledStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDisabledStatus(String value) {
        this.accountDisabledStatus = value;
    }

    /**
     * Gets the value of the postOfficeBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostOfficeBox() {
        return postOfficeBox;
    }

    /**
     * Sets the value of the postOfficeBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostOfficeBox(String value) {
        this.postOfficeBox = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the assignedDepartments property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedDepartments }
     *     
     */
    public AssignedDepartments getAssignedDepartments() {
        return assignedDepartments;
    }

    /**
     * Sets the value of the assignedDepartments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedDepartments }
     *     
     */
    public void setAssignedDepartments(AssignedDepartments value) {
        this.assignedDepartments = value;
    }

    /**
     * Gets the value of the pmlName property.
     * 
     * @return
     *     possible object is
     *     {@link PmlName }
     *     
     */
    public PmlName getPmlName() {
        return pmlName;
    }

    /**
     * Sets the value of the pmlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmlName }
     *     
     */
    public void setPmlName(PmlName value) {
        this.pmlName = value;
    }

    /**
     * Gets the value of the managers property.
     * 
     * @return
     *     possible object is
     *     {@link Managers }
     *     
     */
    public Managers getManagers() {
        return managers;
    }

    /**
     * Sets the value of the managers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Managers }
     *     
     */
    public void setManagers(Managers value) {
        this.managers = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * @return
     *     possible object is
     *     {@link Reports }
     *     
     */
    public Reports getReports() {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reports }
     *     
     */
    public void setReports(Reports value) {
        this.reports = value;
    }

    /**
     * Gets the value of the leadershipCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadershipCategory() {
        return leadershipCategory;
    }

    /**
     * Sets the value of the leadershipCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadershipCategory(String value) {
        this.leadershipCategory = value;
    }

    /**
     * Gets the value of the leadershipCategoryOld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadershipCategoryOld() {
        return leadershipCategoryOld;
    }

    /**
     * Sets the value of the leadershipCategoryOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadershipCategoryOld(String value) {
        this.leadershipCategoryOld = value;
    }

    /**
     * Gets the value of the primOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimOfficeCode() {
        return primOfficeCode;
    }

    /**
     * Sets the value of the primOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimOfficeCode(String value) {
        this.primOfficeCode = value;
    }

    /**
     * Gets the value of the primAgentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimAgentCode() {
        return primAgentCode;
    }

    /**
     * Sets the value of the primAgentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimAgentCode(String value) {
        this.primAgentCode = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the fieldStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldStatus() {
        return fieldStatus;
    }

    /**
     * Sets the value of the fieldStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldStatus(String value) {
        this.fieldStatus = value;
    }

    /**
     * Gets the value of the distChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistChannel() {
        return distChannel;
    }

    /**
     * Sets the value of the distChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistChannel(String value) {
        this.distChannel = value;
    }

    /**
     * Gets the value of the htkRepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtkRepId() {
        return htkRepId;
    }

    /**
     * Sets the value of the htkRepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtkRepId(String value) {
        this.htkRepId = value;
    }

    /**
     * Gets the value of the htkContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtkContract() {
        return htkContract;
    }

    /**
     * Sets the value of the htkContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtkContract(String value) {
        this.htkContract = value;
    }

    /**
     * Gets the value of the pmlContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmlContract() {
        return pmlContract;
    }

    /**
     * Sets the value of the pmlContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmlContract(String value) {
        this.pmlContract = value;
    }

    /**
     * Gets the value of the piaContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiaContract() {
        return piaContract;
    }

    /**
     * Sets the value of the piaContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiaContract(String value) {
        this.piaContract = value;
    }

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the challengeQuestion2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallengeQuestion2() {
        return challengeQuestion2;
    }

    /**
     * Sets the value of the challengeQuestion2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallengeQuestion2(String value) {
        this.challengeQuestion2 = value;
    }

    /**
     * Gets the value of the challengeResponse2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallengeResponse2() {
        return challengeResponse2;
    }

    /**
     * Sets the value of the challengeResponse2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallengeResponse2(String value) {
        this.challengeResponse2 = value;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    /**
     * Gets the value of the sitePhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitePhrase() {
        return sitePhrase;
    }

    /**
     * Sets the value of the sitePhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitePhrase(String value) {
        this.sitePhrase = value;
    }

    /**
     * Gets the value of the cookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * Sets the value of the cookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookie(String value) {
        this.cookie = value;
    }

    /**
     * Gets the value of the lanUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanUser() {
        return lanUser;
    }

    /**
     * Sets the value of the lanUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanUser(String value) {
        this.lanUser = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPin() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPin(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the delegators property.
     * 
     * @return
     *     possible object is
     *     {@link Delegators }
     *     
     */
    public Delegators getDelegators() {
        return delegators;
    }

    /**
     * Sets the value of the delegators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delegators }
     *     
     */
    public void setDelegators(Delegators value) {
        this.delegators = value;
    }

    /**
     * Gets the value of the delegates property.
     * 
     * @return
     *     possible object is
     *     {@link Delegates }
     *     
     */
    public Delegates getDelegates() {
        return delegates;
    }

    /**
     * Sets the value of the delegates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delegates }
     *     
     */
    public void setDelegates(Delegates value) {
        this.delegates = value;
    }

    /**
     * Gets the value of the aesToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAesToken() {
        return aesToken;
    }

    /**
     * Sets the value of the aesToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAesToken(String value) {
        this.aesToken = value;
    }

    /**
     * Gets the value of the hrinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Hrinformation }
     *     
     */
    public Hrinformation getHrinformation() {
        return hrinformation;
    }

    /**
     * Sets the value of the hrinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hrinformation }
     *     
     */
    public void setHrinformation(Hrinformation value) {
        this.hrinformation = value;
    }

    /**
     * Gets the value of the changePasswordOnNextLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangePasswordOnNextLogin() {
        return changePasswordOnNextLogin;
    }

    /**
     * Sets the value of the changePasswordOnNextLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangePasswordOnNextLogin(String value) {
        this.changePasswordOnNextLogin = value;
    }

    /**
     * Gets the value of the passwordExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPasswordExpired() {
        return passwordExpired;
    }

    /**
     * Sets the value of the passwordExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPasswordExpired(Boolean value) {
        this.passwordExpired = value;
    }

    /**
     * Gets the value of the passwordLastSetDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordLastSetDate() {
        return passwordLastSetDate;
    }

    /**
     * Sets the value of the passwordLastSetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordLastSetDate(String value) {
        this.passwordLastSetDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the alternateEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateEmailAddress() {
        return alternateEmailAddress;
    }

    /**
     * Sets the value of the alternateEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateEmailAddress(String value) {
        this.alternateEmailAddress = value;
    }

    /**
     * Gets the value of the subscribedServices property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribedServices }
     *     
     */
    public SubscribedServices getSubscribedServices() {
        return subscribedServices;
    }

    /**
     * Sets the value of the subscribedServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribedServices }
     *     
     */
    public void setSubscribedServices(SubscribedServices value) {
        this.subscribedServices = value;
    }

    /**
     * Gets the value of the userCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCategory() {
        return userCategory;
    }

    /**
     * Sets the value of the userCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCategory(String value) {
        this.userCategory = value;
    }

    /**
     * Gets the value of the msaExclusiveFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsaExclusiveFlag() {
        return msaExclusiveFlag;
    }

    /**
     * Sets the value of the msaExclusiveFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsaExclusiveFlag(String value) {
        this.msaExclusiveFlag = value;
    }

    /**
     * Gets the value of the realtimePosting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealtimePosting() {
        return realtimePosting;
    }

    /**
     * Sets the value of the realtimePosting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealtimePosting(String value) {
        this.realtimePosting = value;
    }

    /**
     * Gets the value of the assignedSourceSystems property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedSourceSystems }
     *     
     */
    public AssignedSourceSystems getAssignedSourceSystems() {
        return assignedSourceSystems;
    }

    /**
     * Sets the value of the assignedSourceSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedSourceSystems }
     *     
     */
    public void setAssignedSourceSystems(AssignedSourceSystems value) {
        this.assignedSourceSystems = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    public User withRoles(Roles value) {
        setRoles(value);
        return this;
    }

    public User withRolesCopy(RolesCopy value) {
        setRolesCopy(value);
        return this;
    }

    public User withDn(String value) {
        setDn(value);
        return this;
    }

    public User withName(String value) {
        setName(value);
        return this;
    }

    public User withDob(String value) {
        setDob(value);
        return this;
    }

    public User withTaxId(String value) {
        setTaxId(value);
        return this;
    }

    public User withPassword(String value) {
        setPassword(value);
        return this;
    }

    public User withOldPassword(String value) {
        setOldPassword(value);
        return this;
    }

    public User withClientId(String value) {
        setClientId(value);
        return this;
    }

    public User withTermsAndConditionsFlag(String value) {
        setTermsAndConditionsFlag(value);
        return this;
    }

    public User withCurrentTermCondFlag(Boolean value) {
        setCurrentTermCondFlag(value);
        return this;
    }

    public User withDisabled(Boolean value) {
        setDisabled(value);
        return this;
    }

    public User withRegistered(Boolean value) {
        setRegistered(value);
        return this;
    }

    public User withConfirmEmail(String value) {
        setConfirmEmail(value);
        return this;
    }

    public User withContractTerminatedFlag(String value) {
        setContractTerminatedFlag(value);
        return this;
    }

    public User withEmailAddress(String value) {
        setEmailAddress(value);
        return this;
    }

    public User withChallengeQuestion(String value) {
        setChallengeQuestion(value);
        return this;
    }

    public User withChallengeResponse(String value) {
        setChallengeResponse(value);
        return this;
    }

    public User withLastName(String value) {
        setLastName(value);
        return this;
    }

    public User withFirstName(String value) {
        setFirstName(value);
        return this;
    }

    public User withMiddleName(String value) {
        setMiddleName(value);
        return this;
    }

    public User withPolicyNo(String value) {
        setPolicyNo(value);
        return this;
    }

    public User withCompany(String value) {
        setCompany(value);
        return this;
    }

    public User withCompanyCode(String value) {
        setCompanyCode(value);
        return this;
    }

    public User withPayGroups(PayGroups value) {
        setPayGroups(value);
        return this;
    }

    public User withDepartment(String value) {
        setDepartment(value);
        return this;
    }

    public User withDepartmentCode(String value) {
        setDepartmentCode(value);
        return this;
    }

    public User withFileNumber(String value) {
        setFileNumber(value);
        return this;
    }

    public User withHireDate(String value) {
        setHireDate(value);
        return this;
    }

    public User withEmployeeId(String value) {
        setEmployeeId(value);
        return this;
    }

    public User withAccountingOfficeCode(String value) {
        setAccountingOfficeCode(value);
        return this;
    }

    public User withEmployeeStatus(String value) {
        setEmployeeStatus(value);
        return this;
    }

    public User withPhone(String value) {
        setPhone(value);
        return this;
    }

    public User withSelfRegDone(String value) {
        setSelfRegDone(value);
        return this;
    }

    public User withRegComplete(String value) {
        setRegComplete(value);
        return this;
    }

    public User withUserId(String value) {
        setUserId(value);
        return this;
    }

    public User withLoginLockedStatus(String value) {
        setLoginLockedStatus(value);
        return this;
    }

    public User withAccountDisabledStatus(String value) {
        setAccountDisabledStatus(value);
        return this;
    }

    public User withPostOfficeBox(String value) {
        setPostOfficeBox(value);
        return this;
    }

    public User withAddress(Address value) {
        setAddress(value);
        return this;
    }

    public User withAuthCode(String value) {
        setAuthCode(value);
        return this;
    }

    public User withPrefix(String value) {
        setPrefix(value);
        return this;
    }

    public User withAssignedDepartments(AssignedDepartments value) {
        setAssignedDepartments(value);
        return this;
    }

    public User withPmlName(PmlName value) {
        setPmlName(value);
        return this;
    }

    public User withManagers(Managers value) {
        setManagers(value);
        return this;
    }

    public User withReports(Reports value) {
        setReports(value);
        return this;
    }

    public User withLeadershipCategory(String value) {
        setLeadershipCategory(value);
        return this;
    }

    public User withLeadershipCategoryOld(String value) {
        setLeadershipCategoryOld(value);
        return this;
    }

    public User withPrimOfficeCode(String value) {
        setPrimOfficeCode(value);
        return this;
    }

    public User withPrimAgentCode(String value) {
        setPrimAgentCode(value);
        return this;
    }

    public User withLocation(Location value) {
        setLocation(value);
        return this;
    }

    public User withFieldStatus(String value) {
        setFieldStatus(value);
        return this;
    }

    public User withDistChannel(String value) {
        setDistChannel(value);
        return this;
    }

    public User withHtkRepId(String value) {
        setHtkRepId(value);
        return this;
    }

    public User withHtkContract(String value) {
        setHtkContract(value);
        return this;
    }

    public User withPmlContract(String value) {
        setPmlContract(value);
        return this;
    }

    public User withPiaContract(String value) {
        setPiaContract(value);
        return this;
    }

    public User withClientType(String value) {
        setClientType(value);
        return this;
    }

    public User withChallengeQuestion2(String value) {
        setChallengeQuestion2(value);
        return this;
    }

    public User withChallengeResponse2(String value) {
        setChallengeResponse2(value);
        return this;
    }

    public User withImageId(String value) {
        setImageId(value);
        return this;
    }

    public User withSitePhrase(String value) {
        setSitePhrase(value);
        return this;
    }

    public User withCookie(String value) {
        setCookie(value);
        return this;
    }

    public User withLanUser(String value) {
        setLanUser(value);
        return this;
    }

    public User withPin(String value) {
        setPin(value);
        return this;
    }

    public User withDelegators(Delegators value) {
        setDelegators(value);
        return this;
    }

    public User withDelegates(Delegates value) {
        setDelegates(value);
        return this;
    }

    public User withAesToken(String value) {
        setAesToken(value);
        return this;
    }

    public User withHrinformation(Hrinformation value) {
        setHrinformation(value);
        return this;
    }

    public User withChangePasswordOnNextLogin(String value) {
        setChangePasswordOnNextLogin(value);
        return this;
    }

    public User withPasswordExpired(Boolean value) {
        setPasswordExpired(value);
        return this;
    }

    public User withPasswordLastSetDate(String value) {
        setPasswordLastSetDate(value);
        return this;
    }

    public User withModifiedDate(String value) {
        setModifiedDate(value);
        return this;
    }

    public User withAlternateEmailAddress(String value) {
        setAlternateEmailAddress(value);
        return this;
    }

    public User withSubscribedServices(SubscribedServices value) {
        setSubscribedServices(value);
        return this;
    }

    public User withUserCategory(String value) {
        setUserCategory(value);
        return this;
    }

    public User withMsaExclusiveFlag(String value) {
        setMsaExclusiveFlag(value);
        return this;
    }

    public User withRealtimePosting(String value) {
        setRealtimePosting(value);
        return this;
    }

    public User withAssignedSourceSystems(AssignedSourceSystems value) {
        setAssignedSourceSystems(value);
        return this;
    }

    public User withStatus(Status value) {
        setStatus(value);
        return this;
    }

}
