/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mpayne' at '6/1/15 2:00 PM' with Gradle 2.4
 *
 * @author mpayne, @date 6/1/15 2:00 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
